version: '3.3'

services:
  # Laravel приложение для нового дизайна
  app_new:
    build: .
    container_name: license_kz_new_app
    ports:
      - "8001:80"  # Другой порт для нового проекта
    volumes:
      # Монтируем только storage и logs для персистентности данных
      - ./storage:/var/www/html/storage
      - ./public/uploads:/var/www/html/public/uploads
    environment:
      # Основные настройки Laravel
      - APP_NAME=UPPERLICENSE_NEW
      - APP_ENV=production
      - APP_KEY=${APP_KEY:-}
      - APP_DEBUG=false
      - APP_URL=http://license.kz:8001
      
      # Настройки базы данных (та же БД что и основной проект)
      - DB_CONNECTION=mysql
      - DB_HOST=${DB_HOST:-localhost}
      - DB_PORT=${DB_PORT:-3306}
      - DB_DATABASE=${DB_DATABASE:-license_kz}
      - DB_USERNAME=${DB_USERNAME:-root}
      - DB_PASSWORD=${DB_PASSWORD:-}
      
      # Настройки кеша и сессий
      - CACHE_DRIVER=file
      - SESSION_DRIVER=file
      - QUEUE_CONNECTION=sync
      
      # Настройки почты
      - MAIL_MAILER=${MAIL_MAILER:-smtp}
      - MAIL_HOST=${MAIL_HOST:-smtp.gmail.com}
      - MAIL_PORT=${MAIL_PORT:-587}
      - MAIL_USERNAME=${MAIL_USERNAME:-}
      - MAIL_PASSWORD=${MAIL_PASSWORD:-}
      - MAIL_ENCRYPTION=${MAIL_ENCRYPTION:-tls}
      - MAIL_FROM_ADDRESS=${MAIL_FROM_ADDRESS:-noreply@license.kz}
      - MAIL_FROM_NAME=${MAIL_FROM_NAME:-UPPERLICENSE}
      
      # Дополнительные настройки
      - RUN_MIGRATIONS=false  # НЕ запускаем миграции, используем существующую БД
      
    restart: unless-stopped
    networks:
      - license_network

  # Redis для кеширования (опционально, можно использовать общий с основным проектом)
  redis_new:
    image: redis:6-alpine
    container_name: license_kz_new_redis
    ports:
      - "6380:6379"  # Другой порт для Redis
    volumes:
      - redis_new_data:/data
    restart: unless-stopped
    networks:
      - license_network

volumes:
  redis_new_data:
    driver: local

networks:
  license_network:
    driver: bridge
