version: '2.2'

services:
  # Laravel приложение
  app:
    build: .
    container_name: license_kz_app
    ports:
      - "8001:80"
    volumes:
      - ./storage:/var/www/html/storage
      - ./public/uploads:/var/www/html/public/uploads
    environment:
      - APP_NAME=UPPERLICENSE
      - APP_ENV=production
      - APP_KEY=${APP_KEY:-}
      - APP_DEBUG=false
      - APP_URL=http://license.kz:8001
      - DB_CONNECTION=mysql
      - DB_HOST=localhost
      - DB_PORT=3306
      - DB_DATABASE=license_kz
      - DB_USERNAME=root
      - DB_PASSWORD=${DB_PASSWORD:-}
      - CACHE_DRIVER=file
      - SESSION_DRIVER=file
      - QUEUE_CONNECTION=sync
      - RUN_MIGRATIONS=false
    restart: unless-stopped
    network_mode: "host"
