version: '3.8'

services:
  # Laravel приложение
  app:
    build: .
    container_name: license_kz
    ports:
      - "8000:80"
    volumes:
      # Только необходимые директории для персистентности
      - ./storage:/var/www/html/storage
      - ./public/uploads:/var/www/html/public/uploads
    environment:
      # Основные настройки
      - APP_NAME=UPPERLICENSE
      - APP_ENV=production
      - APP_DEBUG=false
      - APP_URL=http://localhost:8000
      
      # Подключение к внешней БД
      - DB_CONNECTION=${DB_CONNECTION:-mysql}
      - DB_HOST=${DB_HOST:-host.docker.internal}
      - DB_PORT=${DB_PORT:-3306}
      - DB_DATABASE=${DB_DATABASE:-license_kz}
      - DB_USERNAME=${DB_USERNAME:-root}
      - DB_PASSWORD=${DB_PASSWORD:-}
      
      # Простые настройки для файлового кеша
      - CACHE_DRIVER=file
      - SESSION_DRIVER=file
      - QUEUE_CONNECTION=sync
      
    restart: unless-stopped
